[package]
name = "sync"
version = "0.0.1"
authors = []

[lib]
name = "uu_sync"
path = "sync.rs"

[dependencies]
libc = "*"
winapi = "*"
kernel32-sys = "*"
uucore = { path="../uucore" }

[[bin]]
name = "sync"
path = "main.rs"
