platform:
  - x64

environment:
  global:
    RUSTC_V: nightly

  matrix:
  - TARGET: i686-pc-windows-gnu

install:
  - SET RUSTC_V = %RUSTC_V%
  - ps: . ${Env:APPVEYOR_BUILD_FOLDER}\tooling\build\windows\appveyor.install.ps1
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64

build_script:
  - ps : . ${Env:APPVEYOR_BUILD_FOLDER}\tooling\build\windows\appveyor.common.ps1; mbash("make build")  
#  - 7z a -tzip uutils.zip .\target\release\deps\*.exe
 
#artifacts:
#  - path: uutils.zip
#    name: zipfile
#  - path: target\release\uutils.exe
#    name: uutils.exe

test_script:
  - ps : . ${Env:APPVEYOR_BUILD_FOLDER}\tooling\build\windows\appveyor.common.ps1; mbash("make test")
