platform:
  - x64

environment:
  global:
    RUSTC_V: nightly

  matrix:
  - TARGET: x86_64-pc-windows-msvc
#  - TARGET: i686-pc-windows-msvc
#  - TARGET: x86_64-pc-windows-gnu
#  - TARGET: x86_64-pc-windows-gnu
  

install:
  - SET RUSTC_V = %RUSTC_V%
#- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - set PATH=c:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%
  - ps: . ${Env:APPVEYOR_BUILD_FOLDER}\tooling\build\windows\appveyor.install.ps1  

build_script:
  - true
  # (by default "make build" builds both the individual binaries and
  #  libs of all programs for this platform, whereas make test knows
  #  it only needs to compile libs, and only for programs on this platform with integration tests)
 
#artifacts:
#  - path: uutils.zip
#    name: zipfile
#  - path: target\release\uutils.exe
#    name: uutils.exe

test_script:
  - ps : . ${Env:APPVEYOR_BUILD_FOLDER}\tooling\build\windows\appveyor.common.ps1; mbash("make test")

cache:
  - c:\cache
