platform:
    - x64
environment:
  matrix:
      - RUSTC_V: Nightly
install:
    - set PATH=c:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.msi" -FileName rust.msi
    - ps: mkdir c:\rust
    - ps: ls c:\rust
    - cmd: msiexec /i rust.msi COMPONENTS="rust,cargo" INSTALLDIR="c:\rust" /qn
    - SET PATH=c:\rust\bin;%PATH%
    - ps: rustc -V
    - ps: cargo -V
    
build_script:
    - ps: foreach ($service in get-content $ENV:APPVEYOR_BUILD_FOLDER\tooling\packaging\proglists\generic.integration_tests.txt) { cargo build --features $service --no-default-features }
    
test_script:
    - ps: foreach ($service in get-content $ENV:APPVEYOR_BUILD_FOLDER\tooling\packaging\proglists\generic.integration_tests.txt) { if ( -Not(cargo test --test $service --features $service --no-default-features)) { false; } }
#    - ps: foreach ($service in get-content $ENV:APPVEYOR_BUILD_FOLDER\tooling\packaging\proglists\generic.txt) { cargo test -p $service }    

    
cache:
  - 'target'
  - 'C:\Users\appveyor\.cargo'
