environment:
  global:
    DIR_DOWNLOADS_RS: c:\rust\download\
    DIR_INSTALLS_RS: c:\rust\installed\
    REINSTALL: 0
  
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_DIR: mingw32
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64

install:
  - ps: >-
      $today = Get-Date -UFormat "%Y_%m_%d";
      $env:DIR_NIGHTLY_RS="${env:DIR_INSTALLS_RS}\$today\";
      if (-not (Test-Path -Path "${env:DIR_NIGHTLY_RS}")) {
        $env:INSTALL_RUST=1;
        if (Test-Path -Path "${env:DIR_DOWNLOADS_RS}") { rm -Recurse ${env:DIR_DOWNLOADS_RS}\*; }
        if (Test-Path -Path "${env:DIR_INSTALLS_RS}") { rm -Recurse ${env:DIR_INSTALLS_RS}\*; }
        New-Item -ItemType Directory -Force -Path ${env:DIR_DOWNLOADS_RS} | Out-Null;
        New-Item -ItemType Directory -Force -Path ${env:DIR_INSTALLS_RS} | Out-Null;
        $download_url = "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe";
        Start-FileDownload $download_url -FileName "${env:DIR_DOWNLOADS_RS}\rust.exe";
        Copy-Item "${env:DIR_DOWNLOADS_RS}\rust.exe" "${env:APPVEYOR_BUILD_FOLDER}\rust.exe"
      }
  - SET PATH=%PATH%;%DIR_NIGHTLY_RS%\bin;C:\MinGW\bin

  # Use the system msys if we can
  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%

  # download a custom compiler otherwise
  - if defined MINGW_ARCHIVE appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - if defined MINGW_ARCHIVE 7z x -y "%MINGW_ARCHIVE%" > nul
  - if defined MINGW_ARCHIVE set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%

  - if defined INSTALL_RUST rust.exe /VERYSILENT /NORESTART /DIR="%DIR_NIGHTLY_RS%"

  - rustc -V
  - cargo -V

artifacts:
  - path: target\debug\uutils.exe
    name: uutils.exe

build: false

test_script:
  - cargo test --no-fail-fast --features "nightly generic" --no-default-features

cache:
  - c:\rust\installed
