[package]
name = "timeout"
version = "0.0.1"
authors = []

[lib]
name = "uu_timeout"
path = "timeout.rs"

[dependencies]
libc = "*"
time = "*"
uucore = { path="../uucore" }

[[bin]]
name = "timeout"
path = "main.rs"
