[package]
name = "shuf"
version = "0.0.1"
authors = []

[lib]
name = "uu_shuf"
path = "shuf.rs"

[dependencies]
libc = "*"
rand = "*"
uucore = { path="../uucore" }

[[bin]]
name = "shuf"
path = "main.rs"
