[package]
name = "touch"
version = "0.0.1"
authors = []

[lib]
name = "uu_touch"
path = "touch.rs"

[dependencies]
filetime = "*"
libc = "*"
time = "*"
uucore = { path="../uucore" }

[[bin]]
name = "touch"
path = "main.rs"
