platform:
    - x64
environment:
  matrix:
      - RUSTC_V: Nightly
install:
    - set PATH=c:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.msi" -FileName rust.msi
    - ps: mkdir c:\rust
    - ps: ls c:\rust
    - cmd: msiexec /i rust.msi COMPONENTS="rust,cargo" INSTALLDIR="c:\rust" /qn
    - SET PATH=c:\rust\bin;%PATH%
    - ps: rustc -V
    - ps: cargo -V
    
build_script:
    - cargo build --features="generic" --no-default-features
