[package]
name = "hashsum"
version = "0.0.1"
authors = []

[lib]
name = "uu_hashsum"
path = "hashsum.rs"

[dependencies]
libc = "*"
regex = "*"
regex-syntax = "*"
rust-crypto = "*"
uucore = { path="../uucore" }

[[bin]]
name = "hashsum"
path = "main.rs"
