[package]
name = "sort"
version = "0.0.1"
authors = []

[lib]
name = "uu_sort"
path = "sort.rs"

[dependencies]
libc = "*"
semver = "*"
uucore = { path="../uucore" }

[[bin]]
name = "sort"
path = "main.rs"
