[package]
name = "pinky"
version = "0.0.1"
authors = []

[lib]
name = "uu_pinky"
path = "pinky.rs"

[dependencies]
time = "*"
libc = "^0.2"
uucore = { path="../uucore" }

[[bin]]
name = "pinky"
path = "main.rs"
